### PR TITLE
chore: replace d2-ui-core loading mask with ui-core component

### PR DESCRIPTION
**Pull request by jenniferarnesen**
There is a small workaround (setting z-index on the snackbar) that will be in place until the ui-core snackbar is published.

Setting the z-index enables the snackbar to appear on top of the screencover.

### CODE REVIEW

**Comment by varl** [comment]
https://github.com/dhis2/ui-core/pull/223

This PR should resolve it. I linked it locally and seemed to work. Approve the PR if it works for you!

**Comment by jenniferarnesen** [comment]
The latest from `ui-core` looks good. Just waiting for it to be published.

**Comment by varl** [comment]
@jenniferarnesen **2.2.0** is published and should be ready to use.

**Comment by jenniferarnesen** [comment]
Looks good now. One very minor issue (which I can fix with a style override) is that the material-ui Snackbar appears behind the overlay. (the Snackbar has a default z-index of 1400)

Dashboard screenoverlay

Here is what it looks like when I adjust the Snackbar z-index:

dashboardoverlay-zindexfix

**Review by janhenrikoverland — APPROVED** [review]

**Pull request merged**
