### PR TITLE
chore: automerge all minor dependency PRs

### PR DESCRIPTION
**Pull request by janhenrikoverland**
Would like to wait a bit longer and see how the [kodiak](https://github.com/dhis2/notes/issues/71#issuecomment-716535285) experiments are going. In the meantime I want dependabot to automerge all minor deps.

### CODE REVIEW

**Review by amcgee — COMMENTED** [review]
The code change looks fine, but there is some risk in auto-merging even 3rd party deps.  Will defer to @varl as he's more familiar with the auto-merge strategy

**Comment by janhenrikoverland** [comment]
@amcgee I based it on @varl 's findings:

"My experience (so far) based on validating and merging hundreds of these dependency upgrades over the course of a year is that when quickly merging patch and minor releases they rarely pose a problem"

**Comment by janhenrikoverland** [comment]
@amcgee @varl  We've also had this setting in DV for about a year.

**Comment by varl** [comment]
At the end of the day if we automatically merge dependency updates out of convenience for us, we are going to have something break _eventually_. The question is if we have good enough mechanisms to catch those breakages early and fix them quickly.

I recommend changing the `update_schedule` to 'weekly' or 'monthly':

```
update_schedule: 'daily'
```

**Review by varl — COMMENTED** [review]
See above comment for recommendation about `update_schedule`, other than that I think it's OK.

**Review by varl — APPROVED** [review]

**Comment by janhenrikoverland** [comment]
@varl Thanks and I see your point about `update_schedule`. However part of the strategy is to let dependabot take care of our own @dhis2 dependencies as well, e.g. there's a fix in the DV plugin and we want to propagate it to the dashboard immediately (i.e. same day) without doing that work manually. Is there a way to e.g. set @dhis2 dependencies to `daily` and everything else to `monthly`?

**Comment by varl** [comment]
Not to my knowledge. Ultimately it comes down choosing a strategy that the team is comfortable living with and it sounds like you have that.

In the future we will have another way to quickly propagate dhis2-packages, so then the update schedule can be reconfigured without losing that benefit.

**Comment by janhenrikoverland** [comment]
@varl Good reflections

**Pull request merged**
