### PR TITLE
fix: filter width + input bug

### PR DESCRIPTION
**Pull request by martinkrulltott**
* Sets the filter popup to the correct width (320px, confirmed by @cooper-joe) 
* Fixes a bug where the filter popup would change width when the user starts to type in the filter input field (attached video)

Depends on https://github.com/dhis2/analytics/pull/316

Bug:
ezgif com-video-to-gif

Correct width:
image

### CODE REVIEW

**Review by janhenrikoverland — APPROVED** [review]

**Review by jenniferarnesen — APPROVED** [review]

**Comment by martinkrulltott** [comment]
As pointed out by @jenniferarnesen , this affects the wrapping of long names. They wrap, but are too narrow.
image

Previously, DV dimensions panel (_DP_) and Dashboards DP used to be the same width, which is why this was still working. But since Dashboards DP will now deviate style wise from DV and they're both separated (since the introduction of React Beautiful DnD), can we safely change the width for the DP in Analytics directly? (and fix the wrapping issue at the same time) Rather than passing in a style prop? @janhenrikoverland

**Comment by jenniferarnesen** [comment]
I would say yes. The one in analytics seems to be a custom one for the dashboards now.

**Comment by janhenrikoverland** [comment]
@martinkrulltott @jenniferarnesen Or even move it to dashboards-app?

**Comment by martinkrulltott** [comment]
As the issue was in DimensionItem (thanks for pointing this out @jenniferarnesen ), moving DimensionsPanel wouldn't fix this anyway. Instead I updated DimensionItem (https://github.com/dhis2/analytics/pull/316/commits/ee4eef89b5586c1365f5482d5a411dd594dd36ed) to work in both use cases. Using a hardcoded max-width was a poor implementation anyway (whoopsi), so this solution is better in both regards.

**Review by jenniferarnesen — APPROVED** [review]

**Pull request merged**
