### PR TITLE
chore: replace old mui edit buttons and dialog in dashboard edit view

### PR DESCRIPTION
**Pull request by jenniferarnesen**
Use latest material-ui, or ui-core where applicable

Changes affect edit mode of dashboard:
- Save changes, Delete, Translate and Exit without saving buttons
- Confirm delete dialog

### CODE REVIEW

**Comment by cooper-joe** [comment]
Looks good! I have one request, and that is to switch the order of the translate/delete buttons. So, button order should be Save changes, Translate, Delete.

**Review by cooper-joe — CHANGES_REQUESTED** [review]
Looks good! I have one request, and that is to switch the order of the translate/delete buttons. So, button order should be Save changes, Translate, Delete.

**Review by edoardo — APPROVED** [review]
LGTM

**Review by cooper-joe — APPROVED** [review]

**Comment by jenniferarnesen** [comment]
Use latest material-ui, or ui-core where applicable

Changes affect edit mode of dashboard:

* Save changes, Delete, Translate and Exit without saving buttons
* Confirm delete dialog

**Pull request merged**
