### PR TITLE
fix: bump d2-ui-interpretations and related components for BETA-42 v2.40.0

### PR DESCRIPTION
**Pull request by edoardo**
Backport for the fix for [BETA-42](https://dhis2.atlassian.net/browse/BETA-42)

[BETA-42]: https://dhis2.atlassian.net/browse/BETA-42?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by Philip-Larsen-Donnelly — APPROVED** [review]
Having difficulty testing with netlify - can we merge this and test in the release candidate?

**Comment by edoardo** [comment]
@Philip-Larsen-Donnelly https://pr-2287--dhis2-dashboard.netlify.app/#/ltmvqGkFQyH

Using https://debug.dhis2.org/40.0.0-rc as server, is that correct?

It should be safe to merge anyway, waiting for the checks to pass.

**Comment by Philip-Larsen-Donnelly** [comment]
I was trying on prep server (after setting up nginx and cors whitelist). Is there an AO that demonstrates the issue on debug/40.0.0-rc?

**Comment by edoardo** [comment]
> I was trying on prep server (after setting up nginx and cors whitelist). Is there an AO that demonstrates the issue on debug/40.0.0-rc?

Yes, the dashboard I linked above has the Map with the issue.

**Pull request merged**
